name: coppa
recipe: wordpress
config:
  php: '8.1'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true
services:
  appserver:
    type: php:8.1
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
proxy:
  phpmyadmin:
    - phpmyadmin.coppa.lndo.site
  mailhog:
    - mail.coppa.lndo.site
